watershell:             db 'WATERSH BIN'
microshell:             db 'MICROSH BIN'
securemode:             db 'SECUREMDBIN'
kernel:                 db 'KERNEL  BIN'
test_txt:               db 'TEST    TXT'